 # WELCOME TO NUMPY

In [1]:
import numpy as np


In [2]:
myarry=np.array([[3,5,6,7,89,8]] , np.int8)

In [3]:
myarry

array([[ 3,  5,  6,  7, 89,  8]], dtype=int8)

In [4]:
myarry[0]

array([ 3,  5,  6,  7, 89,  8], dtype=int8)

In [5]:
myarry[0,1]

5

In [6]:
myarry.shape


(1, 6)

In [7]:
myarry.dtype

dtype('int8')

# Array creation : conversation freom other python structure**

In [9]:
listarry=np.array([[1,2,3],[5,6,7],[8,9,10]])

In [10]:
listarry

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
listarry.shape

(3, 3)

In [12]:
listarry.dtype

dtype('int32')

In [13]:
listarry.size


9

In [14]:
np.array({34,45,34})

array({34, 45}, dtype=object)

In [15]:
zeros=np.zeros((2,3))

In [16]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
zeros.shape

(2, 3)

In [18]:
zeros.dtype

dtype('float64')

In [19]:
rng=np.arange(15)

In [20]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,50,10)

In [24]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
emp=np.empty((4,6))

In [26]:
emp


array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        6.23036978e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
        6.23061763e-307, 8.90104239e-307, 6.89804132e-307],
       [1.33512376e-306, 6.89806849e-307, 9.34609790e-307,
        1.69121096e-306, 1.05700515e-307, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        2.11389826e-307, 1.11260619e-306, 5.08887615e-322]])

In [27]:
emp_like=np.empty_like(lspace)

In [28]:
emp_like


array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
ide=np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
arr=np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr=arr.reshape(3,33)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(3, 33)

In [40]:
arr=arr.ravel()

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

In [46]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [48]:
ar=np.array(x)

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
ar.sum(axis=0)

array([12,  8,  9])

In [51]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [52]:
ar.T


array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [54]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
1
0


In [56]:
ar.ndim

2

In [57]:
ar.size

9

In [58]:
ar.nbytes

36

In [59]:
ar.dtype

dtype('int32')

In [60]:
one=np.array([1,3,4,5,66])

In [61]:
one.argmax()

4

In [62]:
one.argmin()

0

In [63]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [66]:
ar.argmin()

8

In [67]:
ar.argmax()

6

In [68]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [69]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [71]:
ar+ ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [73]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [74]:
ar%ar2

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9800\2693754613.py:1: RuntimeWarning: divide by zero encountered in remainder
  ar%ar2


array([[0, 0, 0],
       [0, 0, 0],
       [7, 0, 0]])

In [75]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [76]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [77]:
ar.sum

<function ndarray.sum>

In [78]:
ar.sum()

29

In [79]:
ar.max()

7

In [80]:
ar.min()

0

In [81]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [82]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [83]:
np.count_nonzero(ar)

8